### ISSUE TITLE
delete this page

### ISSUE THREAD

**Issue by drewrehfeld** [drewrehfeld/opened#31]
somehow this page can be found via google: http://drakesnotes.com/who-we-are/

i deleted the page, but i can still find it on google

please delete @asimshahzadmjc

**Comment by asimshahzadmjc** [comment]
@drewrehfeld Actually this page does not exist its the page not found template that was not rendering properly Now I have adjusted the design a bit so that it does not look ugly.
We can have a different styled 404 template for users.
As far as google is concerned google indexes urls for some time that is why it is listing in search results
