### ISSUE TITLE
user problem

### ISSUE THREAD

**Issue by drewrehfeld** [drewrehfeld/opened#34]
see user jwsherer@apu.edu. i created this account as an instructor and it shows that the user owns Zuventurez PITCH, but it looks like they are actually a student? And i do not have the option in wp-admin of selecting them as instructor. please make jwsherer@apu.edu the instructor for this course. and please fix error if their is one.

**Comment by drewrehfeld** [comment]
@asimshahzadmjc please fix this ASAP

**Comment by asimshahzadmjc** [comment]
@drewrehfeld This was fixed during the day. Actually the problem is not with the system also you could have made the user instructor from within the Drakes Notes Administration.
As far as changing role is concerned that can be changed from Wordpress users listing. Although I did changed that already. Please do test this one out and let me know in case of any other issue you may face.

**Comment by drewrehfeld** [comment]
@asimshahzadmjc i tried that and it didn't work... i will test now

**Comment by asimshahzadmjc** [comment]
@drewrehfeld Yes please test that now and let me know if it still did not work

**Comment by drewrehfeld** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/7681590-174733767_4-s1-v1.png?transparent=1&palette=1&width=246)
